export { Login as LoginForm } from './Login'
export { Register as RegisterForm } from './Register'
export { Layout as FormsLayout } from './Layout'
export { Profile as ProfileForm } from './Profile'
export { ChangePass as ChangePassForm } from './ChangePass'
