FROM nginx:latest

# Установка Certbot и необходимых пакетов
RUN apt-get update && apt-get install -y certbot python3-certbot-nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ];
