events {}

http {
    include mime.types;
    access_log /var/log/nginx/access1.log;
    error_log /var/log/nginx/error1.log;

    server {
        listen [::]:443 http2 ssl backlog=2048 ipv6only=off;

        server_name alchemists-team.ya-praktikum.tech;

        ssi on;
        add_header Strict-Transport-Security "max-age=31536000;";
        ssl_ciphers HIGH:!RC4:!aNULL:!eNULL:!MD5:!EXPORT:!EXP:!LOW:!SEED:!CAMELLIA:!IDEA:!PSK:!SRP:!SSLv2;
        ssl_prefer_server_ciphers on;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        ssl_certificate /etc/letsencrypt/live/alchemists-team.ya-praktikum.tech/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/alchemists-team.ya-praktikum.tech/privkey.pem;

        location / {
            proxy_pass http://alc-app:3000;
        }
    }

    server {
        listen 80;
        listen [::]:80;
        server_name alchemists-team.ya-praktikum.tech;
        location / {
            return 301 https://alchemists-team.ya-praktikum.tech$request_uri;
        }
    }
}
